EDA
```{r}
exam <- read.csv("ExamPData.csv", header=TRUE)

table(exam$GPA>=3.5, exam$ExamP)
prop.table(table(exam$GPA>=3.5, exam$ExamP),margin=1)
boxplot(GPA~ExamP, data=exam)

```


Analysis
```{r}
#define the response variable clearly
exam$pass <- ifelse(exam$ExamP=="Passed",1,0)

#model
#log(P(pass|GPA)/P(nopass|GPA))=beta0+beta1GPA
out.exam <- glm(pass~GPA, data=exam, family="binomial")
summary(out.exam)

 #Does GPA have a significant effect on passing?
#z-test - Wald test
summary(out.exam)

#LRT X^2 test
reduced.exam <- glm(pass~+1, data=exam, family="binomial")
anova(reduced.exam, out.exam, test="Chisq")

#95% CI
confint(out.exam)

#for the odds interpretation 
exp(confint(out.exam))[-1,]


#Predict probability for GPA = 3.25, 3.85
predict(out.exam, newdata = data.frame(GPA=c(3.25,3.85)), type = "response")

#Create graphic
#data
plot(pass~GPA, data=exam, xlim=c(0,4))

#Curve of probability
xstar <- seq(0,4,length=100)
phat <- predict(out.exam, newdata=data.frame(GPA=xstar), type="response")
lines(xstar, phat, col="red")
#95% CI
logit.hat <- predict(out.exam, newdata=data.frame(GPA=xstar), type="link", se.fit=TRUE)
logit.l <- logit.hat$fit - 1.96*logit.hat$se.fit
logit.u <- logit.hat$fit + 1.96*logit.hat$se.fit
phat.l <- 1/(1+exp(-logit.l))
phat.u <- 1/(1+exp(-logit.u))
lines(xstar,phat.l, lty=2,col="gray")
lines(xstar,phat.u, lty=2,col="gray")

# ROC Curve
library(ROCR)
ROCRpred <- prediction(predict(out.exam, type='response'), exam$pass)
ROCRperf <- performance(ROCRpred, measure='tpr',x.measure='fpr')
plot(ROCRperf)
abline(0,1)

#AUC
performance(ROCRpred, measure="auc")
```


























