Scottish Hill Races

Class Prep Portion
```{r}
hills <- read.table(header=TRUE, sep="", text="Race	Distance	Climb	Time
Greenmantle	2.5	650	16.083
Carnethy	6	2500	48.35
CraigDunain	6	900	33.65
BenRha	7.5	800	45.6
BenLomond	8	3070	62.267
Goatfell	8	2866	73.217
BensofJura	16	7500	204.617
Cairnpapple	6	800	36.367
Scolty	5	800	29.75
Traprain	6	650	39.75
LairigGhru	28	2100	192.667
Dollar	5	2000	43.05
Lomonds	9.5	2200	65
CairnTable	6	500	44.133
EildonTwo	4.5	1500	26.933
Cairngorm	10	3000	72.25
SevenHills	14	2200	98.417
KnockHill	3	350	78.65
BlackHill	4.5	1000	17.417
CreagBeag	5.5	600	32.567
KildconHill	3	300	15.95
MeallAnt-Suidhe	3.5	1500	27.9
HalfBenNevis	6	2200	47.633
CowHill	2	900	17.933
NBerwickLaw	3	600	18.683
CreagDubh	4	2000	26.217
Burnswark	6	800	34.433
LargoLaw	5	950	28.567
Criffel	6.5	1750	50.5
Acmony	5	500	20.95
BenNevis	10	4400	85.583
Knockfarrel	6	600	32.383
TwoBreweries	18	5200	170.25
Cockleroi	4.5	850	28.1
MoffatChase	20	5000	159.833")

head(hills)
str(hills)

plot(hills$Time~hills$Distance)
plot(hills$Time~hills$Climb)

identify(hills$Climb, hills$Time, plot=TRUE)

```

Class Analysis
```{r}
#Compute Regression Diagnostics

#Fit model using all obs
out.hills <- lm(Time~Distance + Climb, data=hills)

#Leverage
leverage.hills <-lm.influence(out.hills)$hat
subset(leverage.hills, hills$Race=="BenNevis")

#Cook's Distance
cd.hills <- cooks.distance(out.hills)
hills$"Cook's Distance" <- cd.hills
subset(cd.hills, hills$Race=="MoffatChase")

#R-Studentized residuals
R.hills <- rstudent(out.hills)
hills$"R-Studentized Resids" <- R.hills
subset(R.hills, hills$Race=="CairnTable")

#Validate the noramlity assumption
hist(R.hills)

#test of normality
ks.test(R.hills, "pnorm")

#is Kildcon Hill an outlier?
subset(R.hills, hills$Race=="KildconHill")

#is MoffatChase influential?
subset(leverage.hills, hills$Race=="MoffatChase")         #Influencial
subset(cd.hills, hills$Race=="MoffatChase")               #Not Influencial

#Yes... it's OR. Wait, is it good influencial or bad influencial?
par(mfrow=c(1,2))
plot(hills$Distance,hills$Time)
points(hills$Distance[35],hills$Time[35], col="red", pch=19)
plot(hills$Climb,hills$Time)
points(hills$Climb[35],hills$Time[35], col="red", pch=19)
par(mfrow=c(1,1))
#Good influential

#is LairigGhru influencial
subset(leverage.hills, hills$Race=="LairigGhru")         #Influencial
subset(cd.hills, hills$Race=="LairigGhru")               #Influencial

#Yes... it's OR. Wait, is it good influencial or bad influencial?
par(mfrow=c(1,2))
plot(hills$Distance,hills$Time)
points(hills$Distance[11],hills$Time[11], col="red", pch=19)
plot(hills$Climb,hills$Time)
points(hills$Climb[11],hills$Time[11], col="red", pch=19)
par(mfrow=c(1,1))
#Bad influential
#R studentized resid
subset(R.hills, hills$Race=="LairigGhru")     #Bad influential & Outlier

#We should probably remove LairigGhru. It doesn't fit the data we have. A downside to removing the obs is that we have less data and we are grooming out data to fit our model. It's best to specify in our model that our model works best for shorter, modest climb races

#is Cowhill an outlier?
subset(R.hills, hills$Race=="CowHill")
#p value for Ho: CowHill not an outlier
2*(1-pnorm(0.314))          #Fail to reject

#Is KnockHill an outlier?
subset(R.hills, hills$Race=="KnockHill")
2*(1-pnorm(7.61))       #Totally an outlier



```







