Avalanche

Class Prep
```{r}
avalanche <- read.csv("avalanche.txt", header=TRUE, stringsAsFactors = FALSE)

avalanche$my.month <- as.numeric(unlist(strsplit(avalanche$Date,"/"))[seq(1,3*length(avalanche$Date),by=3)])
avalanche$my.year <- as.numeric(unlist(strsplit(avalanche$Date,"/"))[seq(3,3*length(avalanche$Date),by=3)])

avalanche1 <- NULL
for(i in 2000:2018){
  for(j in c(1:3,12)){
    tally <- dim(subset(avalanche,my.year==i & my.month==j,Date))[1]
    avalanche1 <- rbind(avalanche1,c(i,j,tally))
  }
}
avalanche1 <- data.frame(avalanche1)
names(avalanche1) <- c("my.year", "my.month", "Avalanches")

weather <- read.csv("Snow.csv", header=TRUE, stringsAsFactors=FALSE)
weather$my.month <- as.numeric(unlist(strsplit(weather$DATE,"-"))[seq(2,2*length(weather$DATE),by=2)])
weather$my.year <- as.numeric(unlist(strsplit(weather$DATE,"-"))[seq(1,2*length(weather$DATE),by=2)])

avalanche2 <- merge(avalanche1, weather, by=c("my.year","my.month"))
avalanche2 <- avalanche2[,c("my.year","my.month","Avalanches","DT32", "SNOW", "TMIN")]
```

EDA
```{r}
plot(Avalanches~SNOW, data=avalanche2)
plot(Avalanches~TMIN, data=avalanche2)
plot(Avalanches~DT32, data=avalanche2)
```


Class Participation
```{r}
#Model
#Y~Poisson(exp(bet1+beta1 NSOW + beta2 TMIN+ beta3 DT32))

out.avalanche <- glm(Avalanches~SNOW+TMIN+DT32, data=avalanche2, family="poisson")
summary(out.avalanche)

#for interpretation
exp(coef(out.avalanche)[-1])

#95% CI
exp(confint(out.avalanche)[-1,])

red.avalanche <- glm(Avalanches~SNOW, data=avalanche2, family="poisson")
anova(red.avalanche, out.avalanche, test="Chisq")

#predict mean monthly avalanches for typical december
summary(subset(avalanche2, my.month==12))
predict(out.avalanche, newdata=data.frame(SNOW=12.2, TMIN=22.9,DT32=28.0), type="response")
```
















